### ISSUE TITLE
Allow option to not emit errors

### ISSUE THREAD

**Issue by romeovs** [guerrero/stylint-loader#3]
It would be nice to be able to specify that stylist errors do not get emitted as webpack errors.

For example:

```
module.exports = {
  // ...
  stylint: {
    emitErrors: false  
  }
};
```

would still show the errors in the stylint output but would not throw them to webpack, reducing the visual noise in the build output:

```
    ERROR in ./~/css-loader?{"modules":true,"importLoaders":2,"sourceMap":true,"localIdentName":"[local]_[hash:base64:12]","autoprefixer":false}!./~/postcss-loader?{}!./~/stylus-loader?{}!./~/stylint-loader?{"reporter":"stylint-stylish","blocks":false,"brackets":{"expect":"never","error":true},"colons":{"expect":"never","error":true},"colors":{"expect":"always","error":false},"commaSpace":{"expect":"always","error":true},"commentSpace":{"expect":"always","error":true},"cssLiteral":{"expect":"never","error":true},"depthLimit":false,"duplicates":true,"efficient":{"expect":"always","error":false},"extendPref":"@extends","globalDupe":false,"indentPref":2,"leadingZero":{"expect":"never","error":true},"maxErrors":false,"maxWarnings":false,"mixed":false,"namingConvention":"lowercase-dash","namingConventionStrict":true,"none":false,"noImportant":true,"parenSpace":{"expect":"never","error":true},"placeholders":{"expect":"always","error":false},"prefixVarsWithDollar":{"expect":"always","error":false},"quotePref":{"expect":"single","error":true},"semicolons":{"expect":"never","error":true},"sortOrder":false,"stackedProperties":{"expect":"never","error":true},"trailingWhitespace":{"expect":"never","error":true},"universal":{"expect":"never","error":false},"valid":false,"zeroUnits":{"expect":"never","error":true},"zIndexNormalize":false}!./src/ok.styl

    src/ok.styl
      line 7:  unecessary semicolon found

      ✖  1 error

    at DependenciesBlock.<anonymous> (/Users/romeovs/web/wptest/node_modules/webpack/node_modules/webpack-core/lib/NormalModuleMixin.js:79:21)
    at Object.stylint.methods.done (/Users/romeovs/web/wptest/node_modules/stylint-loader/index.js:28:15)
    at Object.doneHandler (/Users/romeovs/web/wptest/node_modules/stylint-stylish/index.js:99:15)
    at Object.exports.default [as reporter] (/Users/romeovs/web/wptest/node_modules/stylint-stylish/index.js:104:24)
    at Object.<anonymous> (/Users/romeovs/web/wptest/node_modules/stylint/src/core/parse.js:44:16)
    at Array.forEach (native)
    at Object.parse (/Users/romeovs/web/wptest/node_modules/stylint/src/core/parse.js:17:13)
    at Object.stylint.methods.read (/Users/romeovs/web/wptest/node_modules/stylint-loader/index.js:12:14)
    at Object.init (/Users/romeovs/web/wptest/node_modules/stylint/src/core/init.js:45:14)
    at /Users/romeovs/web/wptest/node_modules/stylint/node_modules/stampit/stampit.js:88:25
    at forEach (/Users/romeovs/web/wptest/node_modules/stylint/node_modules/stampit/node_modules/mout/array/forEach.js:15:27)
    at Function.factory (/Users/romeovs/web/wptest/node_modules/stylint/node_modules/stampit/stampit.js:86:7)
    at lint (/Users/romeovs/web/wptest/node_modules/stylint-loader/index.js:47:6)
    at Object.module.exports (/Users/romeovs/web/wptest/node_modules/stylint-loader/index.js:71:5)
 @ ./src/ok.styl 4:14-1752 13:2-17:4 14:20-1758
```

vs:

```
   src/ok.styl
      line 7:  unecessary semicolon found

      ✖  1 error
```

**Comment by guerrero** [comment]
Thanks for create an issue @romeovs but I can't reproduce the situation you've described. Can you share the file that creates the output you've described?

I'm using the following configuration:

``` js
// package.json

// ...

"dependencies": {
    "css-loader": "^0.19.0",
    "style-loader": "^0.12.4",
    "stylint": "^1.2.3",
    "stylint-loader": "^0.2.0",
    "stylint-stylish": "^1.2.0",
    "stylus-loader": "^1.3.1",
    "webpack": "^1.12.2"
  }

// ...

// webpack.config.js

// ...

  module: {
    loaders: [
      {
        test: /\.styl$/,
        loader: 'style!css!stylus!stylint',
        exclude: /node_modules/
      }
    ]
  },
  stylint: {
    "reporter": "stylint-stylish",
    "semicolons": {
      "expect": "never",
      "error": true
    }
  }

// ...
```

And this file:

``` stylus
body
  width 10px;
```

And Webpack returns the following output (without the stack trace):

```
Hash: 8006bd108c4b74f26a79
Version: webpack 1.12.2
Time: 1187ms
    Asset     Size  Chunks             Chunk Names
bundle.js  10.7 kB       0  [emitted]  main
   [0] ./main.js 24 bytes {0} [built]
    + 4 hidden modules

ERROR in ./~/css-loader!./~/stylus-loader!./~/stylint-loader!./error.styl



error.styl
  line 2:  unecessary semicolon found

  ✖  1 error
```

**Comment by romeovs** [comment]
The problem is that this is an `ERROR` to webpack. You can view my code at https://github.com/romeovs/wptest, another thing you can see the output. I'm writing a fluent wrapper for webpack configuration in that repo so you might be thrown off by how the syntax looks. I'll try and come up with a MWE that shows the problem soon.

**Comment by romeovs** [comment]
The problem seems to lie with `extract-text-webpack-plugin`. The MWE is at https://gist.github.com/romeovs/0116b8c54e8167546dc6.

**Comment by Jessidhia** [comment]
This should be implementable the same way as eslint-loader did https://github.com/MoOx/eslint-loader/blob/ee4d349/index.js#L62

**Comment by guerrero** [comment]
Sorry, I can't contribute to this repo due that my current workflow has changed and I don't have enough time and motivation to maintain this. Sorry man, you can get more info in #9
